### ISSUE TITLE
loop command bug

### ISSUE THREAD

**Issue by LWJerri** [Jeelanga/JeelangaMusic#16]
1) User can write random numbers or letters and bot repeat this.
2) **loop once** work incorrectly. Must play track 1 time.

**Comment by shaynlink** [comment]
1. If user write random numbers or letters it's as if use did not write anything
2. loop once repeat one music, like spotify and not playlist

**Comment by LWJerri** [comment]
There was a misunderstanding on the part of the user.

**Comment by LWJerri** [comment]
There was a misunderstanding on the part of the user.
