### ISSUE TITLE
Error: input stream: read ECONNRESET. and Error [ERR_STREAM_WRITE_AFTER_END]: input stream: write after end

### ISSUE THREAD

**Issue by ghost** [Jeelanga/JeelangaMusic#31]

**Comment by shaynlink** [comment]
The ECONNRESET error code is due to a poor or unstable connection

**Comment by ghost** [comment]
> The ECONNRESET error code is due to a poor or unstable connection

Error: input stream: read ECONNRESET still same problem and even i have a good connection

**Comment by shaynlink** [comment]
Yes but this problem is in node-opus or discord.js modul, I can't resolve this problem
