### ISSUE TITLE
Time: NaNa

### ISSUE THREAD

**Issue by rmotafreitas** [Jeelanga/JeelangaMusic#34]
When i do now playing command the embed show NaNa in the duration

**Comment by LWJerri** [comment]
Hello! Sorry for the long answer! I know about it, but at this point, I can't vaporize it :(

**Comment by LWJerri** [comment]
I fix it this week.

**Comment by rmotafreitas** [comment]
thx :)

**Comment by LWJerri** [comment]
> thx :)

Hello! I'm fixed the error, wait for new bot version.
