### ISSUE TITLE
Queue music

### ISSUE THREAD

**Issue by TapsHTS** [Jeelanga/JeelangaMusic#35]
Hello ! I have a project to add a system that automatically puts a music via its id in the queue without going through the `play` command. Can you help me ?

**Comment by LWJerri** [comment]
> Hello ! I have a project to add a system that automatically puts a music via its id in the queue without going through the `play` command. Can you help me ?

Hello! Sorry for the late response. You wanna play music without `play` command? How did you plane add music to the queue?

**Comment by TapsHTS** [comment]
It's my question, how can I add directly music to the queue?

**Comment by LWJerri** [comment]
> It's my question, how can I add directly music to the queue?

What do you mean? Can you say me examples?

UPD: I know your question, but I don't know how you want to add music.

**Comment by TapsHTS** [comment]
I want to put one or more musics in the queue by the music ids without going through the command `play` but by the command `queue` (I want to make a backup system playlist) ?

**Comment by LWJerri** [comment]
> I want to put one or more musics in the queue by the music ids without going through the command `play` but by the command `queue` (I want to make a backup system playlist) ?

For example: `queue [video_id]`?

**Comment by TapsHTS** [comment]
This is a playlist in my database: (name: Name of playlist, prop: Author of the playlist, playlist: music in the queue before backing them up)
![image](https://user-images.githubusercontent.com/61658427/101378292-37b76780-38b3-11eb-9523-58efa1d8823a.png)
I want to put the ids in the `playlist` box in the queue to play the music.

**Comment by TapsHTS** [comment]
yes, example: 
`player.queue.load('VpaXK_vXLVc, W5b-a8Nzmag, 4ggMqJ2zKQU, 4bPGxLxogvw')` and it load the music in queue

**Comment by LWJerri** [comment]
> This is a playlist in my database: (name: Name of playlist, prop: Author of the playlist, playlist: music in the queue before backing them up)
> ![image](https://user-images.githubusercontent.com/61658427/101378292-37b76780-38b3-11eb-9523-58efa1d8823a.png)
> I want to put the ids in the `playlist` box in the queue to play the music.

I got it to you! I add this in the new mika version!

UPD: In the actual version, you can't make it.

**Comment by TapsHTS** [comment]
Yes if you want help me before add this in mika, for the test ...

I'm in the last straight, I miss the ways to add music in the queue without going through play

UPD: I already have the commands to add the music to the database and delete it!
2 UPD: I use mysql for this project

**Comment by LWJerri** [comment]
> Yes if you want help me before add this in mika, for the test ...
> 
> I'm in the last straight, I miss the ways to add music in the queue without going through play
> 
> UPD: I already have the commands to add the music to the database and delete it!
> 2 UPD: I use mysql for this project

I plan to use PSQL.

**Comment by TapsHTS** [comment]
> > Yes if you want help me before add this in mika, for the test ...
> > I'm in the last straight, I miss the ways to add music in the queue without going through play
> > UPD: I already have the commands to add the music to the database and delete it!
> > 2 UPD: I use mysql for this project
> 
> I plan to use PSQL.

2 versions x)

**Comment by TapsHTS** [comment]
Tell me when you want to start!

**Comment by LWJerri** [comment]
> Tell me when you want to start!

Okay.

**Comment by TapsHTS** [comment]
> > Tell me when you want to start!
> 
> Okay.

Now 😂

**Comment by LWJerri** [comment]
Don't close issues. I don't have free time to code all my projects.

**Comment by TapsHTS** [comment]
Oh ok sorry 😅

**Comment by LWJerri** [comment]
Hello. Sorry, but I archive this project ;(
