### ISSUE TITLE
Custom user playlist

### ISSUE THREAD

**Issue by LWJerri** [Jeelanga/JeelangaMusic#38]
- **buffer add [URL]** - Add song to user playlist.
- **buffer remove [Position track]** - Remove track from playlist.
- **buffer** - List of all user tracks.
- **buffer play {all}** - Play custom user playlist.

**Comment by TapsHTS** [comment]
> * **buffer add [URL]** - Add song to user playlist.
> * **buffer remove [Position track]** - Remove track from playlist.
> * **buffer** - List of all user tracks.
> * **buffer play {all}** - Play custom user playlist.

Umhhhh... It's for my idea ?

**Comment by LWJerri** [comment]
> > * **buffer add [URL]** - Add song to user playlist.
> > * **buffer remove [Position track]** - Remove track from playlist.
> > * **buffer** - List of all user tracks.
> > * **buffer play {all}** - Play custom user playlist.
> 
> Umhhhh... It's for my idea ?

No. It's other idea.

**Comment by TapsHTS** [comment]
Oh okay !

**Comment by LWJerri** [comment]
Hello. Sorry, but I archive this project ;(
