### ISSUE TITLE
Play with url ?

### ISSUE THREAD

**Issue by TapsHTS** [Jeelanga/JeelangaMusic#41]
Do you have this or no ?

**Comment by LWJerri** [comment]
> Do you have this or no ?

No, but I make it soon.

**Comment by TapsHTS** [comment]
news ?

**Comment by LWJerri** [comment]
> news ?

Hello. I don't have free time to code this project, but in great future, I finish this project.

**Comment by LWJerri** [comment]
Hello. Sorry, but I archive this project ;(
